### ISSUE TITLE
Strings multipe times in ram

### ISSUE THREAD

**Issue by ghost** [circuitsforfun/ESP_Hue#1]
Hi - please put the Strings in PROGMEN and only one time into the memory (a lot of functions use the same strings)

**Comment by rwardlow** [comment]
Thanks for the feedback but almost all strings need to be allocated in RAM because they are dynamic based on user input during the configuration process on the web interface.
There are only 6 instances where I am allocating a fixed string:
String cmd = "{\"on\":";
Those could be put into PROGMEM but it would only save 36 Bytes and I didn't think it was a big deal given that the ESP8266 has 96K Bytes of RAM, they are also local to the function and not static so the RAM is freed up after the function returns. 
On top of that you still have to read data from PROGMEM into RAM to use it anyway so you would end up with the same result of RAM usage storing it in PROGMEM during the execution of the function.
