### ISSUE TITLE
Slow speed response

### ISSUE THREAD

**Issue by tommasoconti98** [circuitsforfun/ESP_Hue#6]
I am trying the example program with a NodeMCU, and when I press the button, at least 5 seconds pass before the light reacts. 
Another request, can you upload more example? Like the ones regarding lights group and brightness/saturation control? Thanks

**Comment by circuitsforfun** [comment]
I'm not sure why it would be that slow, it just sends a request to your Hue Hub and then waits for a response so if it takes that long it might be a networking thing with your specific network configuration, I'm really not sure.... to be honest I haven't touched any of this code in about 5 years other than approving a pull request from someone recently.
I don't even have my Hue light setup anymore where I am living so I don't have a way to test the code to figure out issues or make new examples and I've also moved most of my development from the esp8266 to the esp32 so that would also need to be tested / updated.... I encourage you to dig into the library and see what you can figure out and if you make some improvements please feel free to make a pull request so the changes / fixes can be shared with others!

**Comment by tommasoconti98** [comment]
Thanks for the reply. Unfortunately I'm not so expert with arduino, and that's why I was looking for a library already made to do this thing. Probably I have made some mistake in the editing of the code. Could you give it a quick view?

`#include <WiFiClient.h>
#include <ESP8266WiFi.h>
#include <ESPHue.h>

const char* ssid     = "loreco Wi-Fi";
const char* password = "********";

WiFiClient client;
int Button1 = D2;

ESPHue myHue = ESPHue(client, "**************************", "192.168.1.18", 80);

void setup() {
  pinMode(Button1, INPUT);
  Serial.begin(115200);
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);
  
  WiFi.begin(ssid, password);
  
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");  
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());  
}

void loop() {

  if(digitalRead(Button1) == HIGH) // If Button1 is pressed
  {
      Serial.println("Button1 Pressed");
      if (myHue.getLightState(4) == 1) // If Light 3 is on
      {
          Serial.println("Hue Light 3 is Currently On, Turning Light Off");
          myHue.setLightPower(4, myHue.OFF);
      }
      else // Light 3 is off
      {
          Serial.println("Hue Light 3 is Currently Off, Turning Light On");
          myHue.setLightPower(4, myHue.ON, );
      }
  }
}`


Anyway, could you also tell me how can I turn on lights 4 and 6 simultaneously?
Thank you

**Comment by circuitsforfun** [comment]
Your code looks fine, I don't see any issues... like I said it's been a while since I've touched the code and I don't have my hue lights setup anymore... I know there has been quite a few updates to the Hue Hub and I think even a completely new Hub since I created this so maybe the responses aren't as quick or some other issue? if you just ping your Hub from you computer what is your ping time like? just want to rule out some other networking related issue. Maybe your router... also do you have any kind of http filtering on your router that is maybe checking for certain content? I can't imagine it would cause that long of a delay but just trying to rule out any possibility

There are a couple of ways you can turn on two lights at once... easiest is to add them to a group and then use the setGroupPower method: myHue.setGroupPower(groupNumber, myHue.ON);
If you don't want to create a bunch of groups and you just want to turn two lights on you can just send the command twice, once for each light:
myHue.setLightPower(4, myHue.ON);
myHue.setLightPower(6, myHue.ON);

**Comment by tommasoconti98** [comment]
ok, thanks
